package guis;

import control.ControlRegistrarItinerario;
import java.awt.Graphics;
import java.awt.Image;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import objetos.Guia;
import objetos.Itinerario;
import objetos.Zona;
import org.bson.types.ObjectId;

/**
 *
 * @author R.Pacheco, R.Contreras, E.Villagrana y G.Gaxiola
 */
public class DlgRegistrarItinerario extends javax.swing.JDialog {

    private final ControlRegistrarItinerario control = new ControlRegistrarItinerario();
    
    FondoPanelItinerario fondo = new FondoPanelItinerario();
    
    public DlgRegistrarItinerario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setContentPane(fondo);
        initComponents();
        
        guias = control.recuperaGuiasRegistrados();
        zonas = control.recuperaZonasZoologico();
        
        inicializar();
    }

    private final List<Guia> guias;
    private final List<Zona> zonas;
    private List<JCheckBox> cajasZonas;
    private List<JCheckBox> cajas;
    private List<JTextField> campos;
    
    private void inicializar() {
        cajasZonas = new ArrayList();
        campos = new ArrayList();
        
        cajasZonas.add(ckbZona1);
        cajasZonas.add(ckbZona2);
        cajasZonas.add(ckbZona3);
        cajasZonas.add(ckbZona4);
        cajasZonas.add(ckbZona5);
        cajasZonas.add(ckbZona6);
        cajasZonas.add(ckbZona7);
        cajasZonas.add(ckbZona8);
        cajasZonas.add(ckbZona9);
        
        campos.add(this.campoTextoDuracionItinerario);
        campos.add(this.campoTextoLongitudItinerario);
        campos.add(this.campoTextoNumeroVisitantes);
        campos.add(this.campoDom);
        campos.add(this.campoJue);
        campos.add(this.campoLun);
        campos.add(this.campoMar);
        campos.add(this.campoMie);
        campos.add(this.campoSab);
        campos.add(this.campoVie);
        
        cajas = new ArrayList(cajasZonas);
        cajas.add(this.checkBoxLunes);
        cajas.add(this.checkBoxMartes);
        cajas.add(this.checkBoxMiercoles);
        cajas.add(this.checkBoxJueves);
        cajas.add(this.checkBoxViernes);
        cajas.add(this.checkBoxSabado);
        cajas.add(this.checkBoxDomingo);
        
        if(zonas!=null) {
                for (int i = 0; i < cajasZonas.size(); i++) {
                cajasZonas.get(i).setText(zonas.get(i).getNombre());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Error recuperando las zonas.", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        
        if(guias==null) {
            JOptionPane.showMessageDialog(this, "Error recuperando los guías.", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            cmbGuia.removeAllItems();
            cmbGuia.addItem("Seleccione...");
            for (Guia guia : guias) {
                cmbGuia.addItem(guia.getNombre());
            }
        }
        
        liberarCampos(false);
    }
    
    private void liberarCampos(boolean b) {
        for (JCheckBox caja : cajas) {
            caja.setEnabled(b);
        }
        for (JTextField campo : campos) {
            campo.setEditable(b);
        }
        cmbGuia.setEnabled(b);
        btnGuardarItinerario.setEnabled(b);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnBuscarItinerario = new javax.swing.JButton();
        campoTextoNombreItinerario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoTextoDuracionItinerario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoTextoLongitudItinerario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campoTextoNumeroVisitantes = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbGuia = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        checkBoxDomingo = new javax.swing.JCheckBox();
        checkBoxSabado = new javax.swing.JCheckBox();
        checkBoxViernes = new javax.swing.JCheckBox();
        checkBoxJueves = new javax.swing.JCheckBox();
        checkBoxMiercoles = new javax.swing.JCheckBox();
        checkBoxMartes = new javax.swing.JCheckBox();
        checkBoxLunes = new javax.swing.JCheckBox();
        campoMie = new javax.swing.JTextField();
        campoJue = new javax.swing.JTextField();
        campoMar = new javax.swing.JTextField();
        campoVie = new javax.swing.JTextField();
        campoSab = new javax.swing.JTextField();
        campoDom = new javax.swing.JTextField();
        campoLun = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        ckbZona1 = new javax.swing.JCheckBox();
        ckbZona4 = new javax.swing.JCheckBox();
        ckbZona7 = new javax.swing.JCheckBox();
        ckbZona2 = new javax.swing.JCheckBox();
        ckbZona5 = new javax.swing.JCheckBox();
        ckbZona8 = new javax.swing.JCheckBox();
        ckbZona3 = new javax.swing.JCheckBox();
        ckbZona6 = new javax.swing.JCheckBox();
        ckbZona9 = new javax.swing.JCheckBox();
        btnGuardarItinerario = new javax.swing.JButton();
        btnCancelarItinerario = new javax.swing.JButton();
        btnRegresarItinerario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("REGISTRAR/ACTUALIZAR ITINERARIO DE RECORRIDO");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnBuscarItinerario.setText("Buscar");
        btnBuscarItinerario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarItinerarioActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre itinerario:");

        jLabel2.setText("Duración (minutos):");

        campoTextoDuracionItinerario.setEditable(false);

        jLabel3.setText("Longitud (metros):");

        campoTextoLongitudItinerario.setEditable(false);

        jLabel4.setText("Num. visitantes autorizados:");

        campoTextoNumeroVisitantes.setEditable(false);

        jLabel7.setText("DATOS GENERALES DEL RECORRIDO");
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel8.setText("Guía:");

        cmbGuia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(15, 15, 15)
                                .addComponent(campoTextoNombreItinerario, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(campoTextoNumeroVisitantes, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(campoTextoLongitudItinerario, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarItinerario))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel7))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoTextoDuracionItinerario, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(cmbGuia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscarItinerario)
                    .addComponent(campoTextoNombreItinerario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cmbGuia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoTextoDuracionItinerario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoTextoLongitudItinerario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(campoTextoNumeroVisitantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setText("DÍAS DEL RECORRIDO");
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        checkBoxDomingo.setText("Domingo");
        checkBoxDomingo.setEnabled(false);

        checkBoxSabado.setText("Sábado");
        checkBoxSabado.setEnabled(false);

        checkBoxViernes.setText("Viernes");
        checkBoxViernes.setEnabled(false);

        checkBoxJueves.setText("Jueves");
        checkBoxJueves.setEnabled(false);

        checkBoxMiercoles.setText("Miércoles");
        checkBoxMiercoles.setEnabled(false);

        checkBoxMartes.setText("Martes");
        checkBoxMartes.setEnabled(false);

        checkBoxLunes.setText("Lunes");
        checkBoxLunes.setEnabled(false);
        checkBoxLunes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxLunesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkBoxMartes)
                                    .addComponent(checkBoxMiercoles)
                                    .addComponent(checkBoxJueves)
                                    .addComponent(checkBoxViernes)
                                    .addComponent(checkBoxSabado)
                                    .addComponent(checkBoxDomingo))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(campoMar, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(campoMie, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(campoJue, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(campoVie)
                                            .addComponent(campoSab)
                                            .addComponent(campoDom)))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(checkBoxLunes)
                                .addGap(26, 26, 26)
                                .addComponent(campoLun, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBoxLunes)
                    .addComponent(campoLun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBoxMartes)
                    .addComponent(campoMar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBoxMiercoles)
                    .addComponent(campoMie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBoxJueves)
                    .addComponent(campoJue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBoxViernes)
                    .addComponent(campoVie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBoxSabado)
                    .addComponent(campoSab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBoxDomingo)
                    .addComponent(campoDom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setText("ZONAS DEL RECORRIDO");
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        ckbZona1.setText("1-ALFA");
        ckbZona1.setEnabled(false);

        ckbZona4.setText("2-ALFA");
        ckbZona4.setEnabled(false);

        ckbZona7.setText("3-ALFA");
        ckbZona7.setEnabled(false);

        ckbZona2.setText("1-BETA");
        ckbZona2.setEnabled(false);

        ckbZona5.setText("2-BETA");
        ckbZona5.setEnabled(false);

        ckbZona8.setText("3-BETA");
        ckbZona8.setEnabled(false);

        ckbZona3.setText("1-CHARLIE");
        ckbZona3.setEnabled(false);

        ckbZona6.setText("2-CHARLIE");
        ckbZona6.setEnabled(false);

        ckbZona9.setText("3-CHARLIE");
        ckbZona9.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(321, 321, 321))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ckbZona4)
                    .addComponent(ckbZona1)
                    .addComponent(ckbZona7))
                .addGap(55, 55, 55)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(ckbZona2)
                        .addGap(58, 58, 58)
                        .addComponent(ckbZona3))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ckbZona5)
                            .addComponent(ckbZona8))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ckbZona6)
                            .addComponent(ckbZona9))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbZona1)
                    .addComponent(ckbZona2)
                    .addComponent(ckbZona3))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbZona4)
                    .addComponent(ckbZona5)
                    .addComponent(ckbZona6))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbZona7)
                    .addComponent(ckbZona8)
                    .addComponent(ckbZona9))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        btnGuardarItinerario.setText("Guardar");
        btnGuardarItinerario.setEnabled(false);

        btnCancelarItinerario.setText("Cancelar");

        btnRegresarItinerario.setText("Regresar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(btnGuardarItinerario)
                .addGap(125, 125, 125)
                .addComponent(btnCancelarItinerario)
                .addGap(125, 125, 125)
                .addComponent(btnRegresarItinerario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarItinerario)
                    .addComponent(btnCancelarItinerario)
                    .addComponent(btnRegresarItinerario))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(144, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void checkBoxLunesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxLunesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxLunesActionPerformed

    private void btnBuscarItinerarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarItinerarioActionPerformed
        buscar();
    }//GEN-LAST:event_btnBuscarItinerarioActionPerformed

    
    private void buscar() {
        Itinerario itinerario = control.buscarItinerario(campoTextoNombreItinerario.getText());
        if(itinerario!=null) {
            inicializar();
            
            int indiceGuia = relacionarGuia(itinerario);
            if(indiceGuia==-1) {
                JOptionPane.showMessageDialog(this, "No se ha encontrado el guía del itinerario.", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
            this.cmbGuia.setSelectedIndex(indiceGuia+1);
            
            this.campoTextoDuracionItinerario.setText(String.valueOf(itinerario.getDuracionDelRecorrido()));
            this.campoTextoLongitudItinerario.setText(String.valueOf(itinerario.getLongitud()));
            this.campoTextoNumeroVisitantes.setText(String.valueOf(itinerario.getNumeroMaximoVisitantes()));
            
            for (int i = 0; i < cajasZonas.size(); i++) {
                if(itinerario.getIdsZonasVisitadas().contains(zonas.get(i).getId()))
                    cajasZonas.get(i).setSelected(true);
            }
            
            List<LocalDateTime> horas = itinerario.getDiasYHoras();
            for (LocalDateTime hora : horas) {
                JTextField campo = null;
                JCheckBox caja = null;
                switch(hora.getDayOfWeek().getValue()) {
                    case 1: campo = this.campoLun; caja = this.checkBoxLunes; break;
                    case 2: campo = this.campoMar; caja = this.checkBoxMartes; break;
                    case 3: campo = this.campoMie; caja = this.checkBoxMiercoles; break;
                    case 4: campo = this.campoJue; caja = this.checkBoxJueves; break;
                    case 5: campo = this.campoVie; caja = this.checkBoxViernes; break;
                    case 6: campo = this.campoSab; caja = this.checkBoxSabado; break;
                    case 7: campo = this.campoDom; caja = this.checkBoxDomingo; break;
                }
                agregarHoraAlCampo(campo,hora);
                caja.setSelected(true);
            }
            
        } else {
            JOptionPane.showMessageDialog(this, "No se ha encontrado otro itinerario con ese nombre.\n"
                    +"Se van a habilitar los campos para el registro.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            liberarCampos(true);
        }
        
    }
    
    private void agregarHoraAlCampo(JTextField campo, LocalDateTime hora) {
        String texto = campo.getText();
        
        int h = hora.getHour();
        int m = hora.getMinute();
        
        String horaTexto = (h<10?"0":"")+String.valueOf(h) + ":" + (m<10?"0":"")+String.valueOf(m);
        
        texto = texto + (texto.equals("")?"":", ") + horaTexto;
        
        campo.setText(texto);
    }
    
    private int relacionarGuia(Itinerario itinerario) {
        int indice = -1;
        for (int i = 0; i < guias.size(); i++) {
            for (ObjectId idItinerario : guias.get(i).getItinerariosActuales()) {
                if(itinerario.getId().equals(idItinerario)) indice = i;
            }
        }
        return indice;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarItinerario;
    private javax.swing.JButton btnCancelarItinerario;
    private javax.swing.JButton btnGuardarItinerario;
    private javax.swing.JButton btnRegresarItinerario;
    private javax.swing.JTextField campoDom;
    private javax.swing.JTextField campoJue;
    private javax.swing.JTextField campoLun;
    private javax.swing.JTextField campoMar;
    private javax.swing.JTextField campoMie;
    private javax.swing.JTextField campoSab;
    private javax.swing.JTextField campoTextoDuracionItinerario;
    private javax.swing.JTextField campoTextoLongitudItinerario;
    private javax.swing.JTextField campoTextoNombreItinerario;
    private javax.swing.JTextField campoTextoNumeroVisitantes;
    private javax.swing.JTextField campoVie;
    private javax.swing.JCheckBox checkBoxDomingo;
    private javax.swing.JCheckBox checkBoxJueves;
    private javax.swing.JCheckBox checkBoxLunes;
    private javax.swing.JCheckBox checkBoxMartes;
    private javax.swing.JCheckBox checkBoxMiercoles;
    private javax.swing.JCheckBox checkBoxSabado;
    private javax.swing.JCheckBox checkBoxViernes;
    private javax.swing.JCheckBox ckbZona1;
    private javax.swing.JCheckBox ckbZona2;
    private javax.swing.JCheckBox ckbZona3;
    private javax.swing.JCheckBox ckbZona4;
    private javax.swing.JCheckBox ckbZona5;
    private javax.swing.JCheckBox ckbZona6;
    private javax.swing.JCheckBox ckbZona7;
    private javax.swing.JCheckBox ckbZona8;
    private javax.swing.JCheckBox ckbZona9;
    private javax.swing.JComboBox<String> cmbGuia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables

    class FondoPanelItinerario extends JPanel{
        private Image imagen;
        
        @Override
        public void paint(Graphics g){
            
            imagen = new ImageIcon(getClass().getResource("/imagenes/FondoMenuPrincipal.jpg")).getImage();
            
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            
            setOpaque(false);
            
            super.paint(g);
        }
    }

}
